import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Button} from 'antd'
import {signInWithPopup, GoogleAuthProvider} from 'firebase/auth'
import {auth} from '../firebase_config/firebase'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const googleProvider = new GoogleAuthProvider();

  const signInWithGoogle = async () => {
    try {
      const res = await signInWithPopup(auth, googleProvider);
    } catch (err) { 
      alert(err);
    }
  }
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <center>
          <div>
            <Button
              type="primary"
              className="login-form-button"
              style={{
                width: "100%",
                height: "5vh",
                backgroundColor: "#1a72ee",
              }}
              onClick={signInWithGoogle}
            >
                <h4 style={{ color: "#FFFFFF", paddingTop: "5px" }}>
                  Sign in with Google
                </h4>
              </Button>
            </div>
          </center>
      </main>
    </>
  )
}
